apiVersion: v1
kind: Service
metadata:
  name: servicio-app-2
  labels:
    name: despliegue-app-2
    app: despliegue-app-2
spec:
  type: NodePort
  selector:
    app: despliegue-app-2
  ports:
    - protocol: TCP
      port: 4500
      nodePort: 30127